### PR TITLE
Fix Logout

### LINKED ISSUE #11: Logout button
Make a logout button and update/make the placeholder "logged in" and "bona fide" tags prettier

1. Investigate ELIXIR AAI access token expiration endpoint
  1.1. https://login.elixir-czech.org/oidc/.well-known/openid-configuration has `end_session_endpoint`

### PR DESCRIPTION
**Pull request by teemukataja**
Logout button didn't work, because the UI couldn't overwrite a cookie at the domain level.

New logout procedure uses the auth api, and revokes the token at AAI in addition to deleting the cookie (which is good) https://github.com/CSCfi/oidc-client/pull/13

Fixes #11

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -14,20 +14,14 @@
...
-      <b-button
-        v-if="getCookie('logged_in')"
-        class="login"
-        v-on:click="logOut"
-        type="is-primary"
-        size="is-medium"
-        >Log Out</b-button
-      >
+      <a v-if="getCookie('logged_in')" class="login" :href="logout_url">
+        <b-button class="login" type="is-primary" size="is-medium"
```
Comment (blankdots) [inline src/App.vue]: would be nice to fix this design of the `Logout` button to make it a bit more consistent than:
image

A suggestion for improvement would be:
1. remove the logged in or add a the elixir user id/user name instead 
   * if decision is to keep it probably make the log in as a text instead of a `tag`
2. make the `log out` button of default size by removing the `size="is-medium"`

Comment (teemukataja) [reply src/App.vue]: Done
